import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  "use server";
  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {user.isSignedIn ? (
          <SignOutButton>
            <button className="rounded-md bg-orange-500 p-3.5 text-white">
              Sign Out
            </button>
          </SignOutButton>
        ) : (
          <SignInButton>
            <button className="rounded-md bg-orange-500 p-3.5 text-white">
              Sign In
            </button>
          </SignInButton>
        )}
      </main>
    </>
  );
};

export default Home;
